ZSH=$HOME/.oh-my-zsh

ZSH_CUSTOM=~/.dotfiles/zsh/custom

ZSH_THEME="brafales"

plugins=(brew rake history jump)

source $ZSH/oh-my-zsh.sh

#Don't share history between sessions
unsetopt share_history
setopt no_share_history

#Source specific settings
for file in ~/.dotfiles/zsh/*.zsh; do
    source $file
done

# Bump file descriptors limit for Mac OS X
ulimit -S -n 2048
